# Generated by Django 2.2.16 on 2022-08-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comment_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
    ]
